language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
env:
- EMBER_TRY_SCENARIO=default
- EMBER_TRY_SCENARIO=ember-1.13
- EMBER_TRY_SCENARIO=ember-release
- EMBER_TRY_SCENARIO=ember-beta
- EMBER_TRY_SCENARIO=ember-canary
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
- npm config set spin false
- npm install -g npm@^2
install:
- npm install -g bower
- npm install
- bower install
script:
- ember try $EMBER_TRY_SCENARIO test
notifications:
  slack:
    secure: Z4NJ6lC5z0jHGdh5k2mzNgIPe+S5Hrt826XL6aREQ2KZZE/crmHHx/2j7XpRZa1yRDB/T3unIdAidE1h26mR6yus7gxetGYu/PkWZtd/r6AYLX5DGoifHr7nNuOweCy4yNrqF2WcXyvc8KJE73wj65Hs3+CMLl/uudGh2Q2SZqcGp8sPl9CaiwdYRGo65Uk0RKSLLShCPBPqKljpNLEKbCXWc24HgH6ondtWaeN5zuk16Fw/s/dEmmL6xZw8NAKXWedcl50hy+/3JIowZOYcVtkhqc9aqbKSVd4B2wCuMEFsGRDkmqd1vKF1FskrSujJK1uFGiuJYYwpjIQGaYmOpWEC7U2TeKd7Y+t84psfLKXjln+LPTgtEjf+FEkqThda1qAPRaxxrCfH9Lc6uvB+Ss9sp9hc1ORFcAnYw/Qy3bbGIW/w3rFXUQi9GXsEogNH1/pedgFZV+LZYryC6O6w0Fhs+N5EpCk/NeUDX4ZpyR1V7i7fxkvdo6mE66paTeDQRcvDivC0wUZabO781ze/BiVptqKI9AvUUOrndiiSkxpU0ItxVFewAuITMaMmqL0z5zj/6PXAF83Jl60Jwlb66sqmhRIrto/aCA+IGsd72LLMecq3Jim9N5E1w9wyRDCdQ7H7TntQKFBN5eXIpwca5EuqcksBCeqiT3AhRv13jvw=
deploy:
  provider: heroku
  api_key:
    secure: Sx8sT0IbRCe+u0coJGDLDGUxjnXjfdciCZSCpjotN5l6CrV5zNtKkZP/HWfjYdb8hlcUtvfach3jNUArg4pYNK7m+16d/0JGGjG4eiOPxkk0n5B3anXSL/NUMgtsEJWAxLioD02Zy4tN65xkODM9Jw8zT7V21yB9106OOIaFwqlhZ5wSWIq+VaGji3sVYB18sWhnvvZd4+5nJWY8a5DAH4RzXDSSQe6ZdLlvrG/qglvtUsCfrx6//zHOoYBP56FRFqCIioY168SF54TRQtA4vuHoaDlw15zvVZzuHhlzCK7bnMsM6fnZJXhvNyFBduxaIggnRkHef1ib30Rx5rm6+lCeGINBYD+4wnibZ2IxIRtsCXntjZEZhDJkR801/+VhZKM012LryW/f0y2wa6Mj2uVRtCfWVA2cHtNjAejA+kADPVNbI7slEqI+tM6IdCOAmZ4PygpobetmvrDgkOV3anvZfP8vCzT5yi92xu5SiDiBDC5e0MYh1QdFUIFCqsle0KBgSMgAUU1v5c6WJQeFCpsps9jwZTD6Td9Qrsj1n/h5Mq9SzHmF7wvH8SAHslHiz3D7MRaQ5TFgmBtn4i9XMUYToOuNJ/EACc7fcZgAZ4tG98vnYl0fIUmrQKqDPS+701RHthGJhsm9x68O766KF5DanE7vUc0BR4IrnI+gYkE=
  app: ember-windoc
  on:
    repo: levanto-financial/ember-windoc
